cmake_minimum_required(VERSION 3.0)
project(SkySouldInstaller)

set(CPACK_PACKAGE_NAME "SkySoul")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_VENDOR "Your Company")
set(CPACK_PACKAGE_DESCRIPTION "Your application description")
set(CPACK_PACKAGE_FILE_NAME "SkySoul-${CPACK_PACKAGE_VERSION}")
set(CPACK_PACKAGE_ICON "path/to/your/app_icon.icns")
set(CPACK_RESOURCE_FILE_LICENSE "path/to/your/LICENSE.txt")